### ISSUE TITLE
support for .vtu (VTK/Paraview) files

### ISSUE THREAD

**Issue by MariusCausemann** [jiangzhongshi/bichon#12]
Hi,
I prefer using ParaView for scientific visualizations and wrote a little script to convert the .h5 files into .vtu files suitable for ParaView. Here is an example of the bunny in Paraview:
![bunny](https://user-images.githubusercontent.com/25132217/193289382-b885bf76-2687-4b1b-8f95-9f7f58d158a7.png)
I could prepare a small PR if there is interest in that?

**Comment by jiangzhongshi** [comment]
That's amazing and I would very much appreciate a PR!
