### ISSUE TITLE
compiling error in windows(vs2019)

### ISSUE THREAD

**Issue by Whalesea-Gustav** [jiangzhongshi/bichon#6]
Hello, I find your work is interesting and want to learn about shell generation and high-order mesh generation. I tried to compile the project in Windows with vs2019. I successfully used cmake to configure and generate vs2019 project, but met some problems when building the cumin_bin. I don`t know how to solve them. Can you help me? and can you give some instructions about runing the bichon project in Windows?
![image](https://user-images.githubusercontent.com/40590729/136782793-716f8630-8476-454f-9ef2-c6058eb5d27f.png)

**Comment by Whalesea-Gustav** [comment]
this shows the first two errors
![image](https://user-images.githubusercontent.com/40590729/136783196-c7b10d1a-4cbd-4443-a5f5-837c40c29de8.png)

**Comment by Whalesea-Gustav** [comment]
> Hi,
> 
> Thanks for your interest in our work. I have tested on VS2020, which should work fine.
> 
> It is likely your problem is related to https://stackoverflow.com/questions/62370027/namespace-std-does-not-contain-optional, Can you try enable the flag `/std:c++17 ` ?
> 
> If you have any questions about our paper, don't hesitate to ask :)



> Hi,
> 
> Thanks for your interest in our work. I have tested on VS2020, which should work fine.
> 
> It is likely your problem is related to https://stackoverflow.com/questions/62370027/namespace-std-does-not-contain-optional, Can you try enable the flag `/std:c++17 ` ?
> 
> If you have any questions about our paper, don't hesitate to ask :)

I tried to add the /std:c++17, and update my boost library, and most of errors were eliminated. But there are still some errors related to bichon\external\libigl\include\igl\unique_rows.cpp. It reports like that 
![image](https://user-images.githubusercontent.com/40590729/137087205-3d89d976-be56-40bc-a096-bb2c4d96d259.png)

and all of errors point to these two line codes:
![image](https://user-images.githubusercontent.com/40590729/137087315-347778c0-3a8f-4181-8960-9ce08698c619.png)
 
Do you have any idea about it?

**Comment by jiangzhongshi** [comment]
hi, Does it work for release mode?
